name: destroy-workflow

on:
  workflow_dispatch:
env:
  VPC: gitanshu
  TFSTATE_FILE: VPC.tfstate
  aws_region: us-east-1

jobs:
    destroy_vpc:
      name: destroy
      runs-on: ubuntu-latest
      steps:
        - name: CheckOut
          uses: actions/checkout@v3
        - name: set up terraform hasicrop
          uses: hashicorp/setup-terraform@v1

        - name: configure aws cridentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
            aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
            aws-session-token: ${{ secrets.AWSSESSIONTOKEN }}
            aws-region: ${{env.aws_region}}
  
        - name: terraform init
          run: |
            cd main
            terraform init -reconfigure -backend-config="bucket=${{ env.BUCKET }}" -backend-config="key=${{ env.TFSTATE_FILE }}" -backend-config="region=${{ env.aws_region }}"
            
        - name: destroy
          run: |
            cd main
            terraform destroy -auto-approve
