name: woekflow-deployment

on:
  workflow_dispatch:
     inputs : 
      region :
        description: "Enter your region : "
        required: true  
        type: string    

env:
  VPC: gitanshu
  TFSTATE_FILE: VPC.tfstate
  aws_region: ${{ github.event.inputs.region }}

jobs:
  vpc :
      runs-on : ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Terraform hashicorp setup
          uses: hashicorp/setup-terraform@v2

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
            aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
            aws-session-token: ${{ secrets.AWSSESSIONTOKEN }}
            aws-region: ${{ env.aws_region }}

        - name: terraform init
          run: |
            cd main
             terraform init -reconfigure -backend-config="bucket=${{ env.BUCKET }}" -backend-config="key=${{ env.TFSTATE_FILE }}" -backend-config="region=${{ env.aws_region }}"
        - name: terraform plan
          run: |
           cd main
            terraform plan
        - name: terraform apply
          run: |
            cd main 
              terraform apply -auto-approve
