name : "Terraform_Workflow"

on:
 workflow_dispatch:
  inputs:
   region:
   description: "Enter your region: "
   required: true
   type: string
  
jobs:
 terraform:
  name: "Terraform"
  runs-on: window-latest
  env:
   AWS_ACCESS_KEY_ID: ${{secrets.AWSACCESSKEYID}}
   AWS_SECRET_ACCESS_ID: ${{secrets.AWSSECRETACCESSKEY}}
defaults:
 run:
   working-directory: main
steps:
    - uses: action/checkout@v2
    - uses: action/setup-terraform@v2
    - name: checkout
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
       terraform_version: 1.0.1
       terraform_wrapper: false
     
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
    - name: Terraform Init
      id: init
      run: terraform init
    - name: Terraform Plan
      id: plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply -auto-approve
    
     
  
  
